name: Deploy Next.js application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "NEXT_PUBLIC_API_URL=${{ env.NEXT_PUBLIC_API_URL }}" >> .env && echo "SITE_URL=${{ env.NEXT_PUBLIC_API_URL2 }}" >> .env
      - name: Build docker image
        run: docker build -t hub.mydevpartner.website/yes-no-boys .
      - name: Login to Gohash Docker Registry
        uses: docker/login-action@v3
        with:
          registry: hub.mydevpartner.website
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish image to Personal Docker Registry
        run: docker push hub.mydevpartner.website/yes-no-boys:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to Gohash Docker Registry
        uses: docker/login-action@v3
        with:
          registry: hub.mydevpartner.website
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull image from Personal Docker Registry
        run: docker pull hub.mydevpartner.website/yes-no-boys:latest
      - name: Delete old container
        run: docker rm -f yes-no-boys-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name yes-no-boys-container hub.mydevpartner.website/yes-no-boys
